"""Narrow BrsApi TSETMC unadjusted-daily-candle integration surface."""

from bisfin.integrations.brsapi.client import (
    BRSAPI_CANDLESTICK_PATH,
    BRSAPI_SYMBOL_PATH,
    BRSAPI_UNADJUSTED_DAILY_TYPE,
    BrsApiClient,
    BrsApiSymbolClient,
    FixtureBrsApiClient,
    FixtureBrsApiSymbolClient,
    HttpxBrsApiClient,
    HttpxBrsApiSymbolClient,
)
from bisfin.integrations.brsapi.contracts import (
    BrsApiCandlestickResponse,
    BrsApiCandlestickRow,
    BrsApiConfigurationError,
    BrsApiContractError,
    BrsApiError,
    BrsApiFixtureError,
    BrsApiHttpError,
    BrsApiMalformedResponseError,
    BrsApiNoDataResponse,
    BrsApiProviderError,
    BrsApiRawResponse,
    BrsApiSymbolMetadata,
    BrsApiTimeoutError,
    BrsApiTransportError,
    DailyBarParseResult,
    ParsedDailyBarCandidate,
    RowValidationCode,
    RowValidationIssue,
    RowValidationResult,
)
from bisfin.integrations.brsapi.normalization import (
    normalize_brsapi_symbol,
    normalize_digits,
    parse_jalali_date,
    parse_source_time,
)
from bisfin.integrations.brsapi.parser import (
    canonical_json_bytes,
    parse_candlestick_envelope,
    parse_unadjusted_daily_candles,
    response_payload_sha256,
    row_payload_sha256,
)
from bisfin.integrations.brsapi.symbol import parse_symbol_metadata

__all__ = [
    "BRSAPI_CANDLESTICK_PATH",
    "BRSAPI_SYMBOL_PATH",
    "BRSAPI_UNADJUSTED_DAILY_TYPE",
    "BrsApiCandlestickResponse",
    "BrsApiCandlestickRow",
    "BrsApiClient",
    "BrsApiSymbolClient",
    "BrsApiConfigurationError",
    "BrsApiContractError",
    "BrsApiError",
    "BrsApiFixtureError",
    "BrsApiHttpError",
    "BrsApiMalformedResponseError",
    "BrsApiNoDataResponse",
    "BrsApiProviderError",
    "BrsApiRawResponse",
    "BrsApiSymbolMetadata",
    "BrsApiTimeoutError",
    "BrsApiTransportError",
    "DailyBarParseResult",
    "FixtureBrsApiClient",
    "FixtureBrsApiSymbolClient",
    "HttpxBrsApiClient",
    "HttpxBrsApiSymbolClient",
    "ParsedDailyBarCandidate",
    "RowValidationCode",
    "RowValidationIssue",
    "RowValidationResult",
    "canonical_json_bytes",
    "normalize_brsapi_symbol",
    "normalize_digits",
    "parse_candlestick_envelope",
    "parse_jalali_date",
    "parse_source_time",
    "parse_symbol_metadata",
    "parse_unadjusted_daily_candles",
    "response_payload_sha256",
    "row_payload_sha256",
]
