"""Query-only SQLAlchemy Core metadata for the existing ``backtest`` schema.

Raw SQL migrations remain the sole schema authority.  This metadata is kept
separate from the compact catalog/market mapping surface so existing consumers
do not accidentally acquire a larger reflection contract.
"""

from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    Float,
    Integer,
    Interval,
    MetaData,
    Numeric,
    SmallInteger,
    Table,
    Text,
)
from sqlalchemy.dialects.postgresql import CHAR, JSONB, TIMESTAMP, VARCHAR

backtest_metadata = MetaData()
_money = Numeric(38, 18)
_ts = TIMESTAMP(timezone=True, precision=6)

strategy = Table(
    "strategy",
    backtest_metadata,
    Column("strategy_id", BigInteger, primary_key=True),
    Column("strategy_code", VARCHAR(128), nullable=False),
    Column("display_name", Text, nullable=False),
    Column("description", Text),
    Column("owner_name", Text),
    Column("created_at", _ts, nullable=False),
    schema="backtest",
)
strategy_version = Table(
    "strategy_version",
    backtest_metadata,
    Column("strategy_version_id", BigInteger, primary_key=True),
    Column("strategy_id", BigInteger, nullable=False),
    Column("version_no", Integer, nullable=False),
    Column("class_path", Text, nullable=False),
    Column("code_sha256", CHAR(64), nullable=False),
    Column("code_uri", Text),
    Column("parameter_schema", JSONB, nullable=False),
    Column("default_parameters", JSONB, nullable=False),
    Column("created_at", _ts, nullable=False),
    Column("deprecated_at", _ts),
    schema="backtest",
)
run = Table(
    "run",
    backtest_metadata,
    Column("run_id", BigInteger, primary_key=True),
    Column("run_code", VARCHAR(128), nullable=False),
    Column("strategy_version_id", BigInteger, nullable=False),
    Column("data_snapshot_id", BigInteger, nullable=False),
    Column("universe_id", BigInteger, nullable=False),
    Column("timeframe_id", SmallInteger),
    Column("base_currency_code", VARCHAR(12), nullable=False),
    Column("event_from", _ts, nullable=False),
    Column("event_to", _ts, nullable=False),
    Column("knowledge_cutoff_ts", _ts, nullable=False),
    Column("availability_mode", VARCHAR(24), nullable=False),
    Column("initial_capital", _money, nullable=False),
    Column("parameters", JSONB, nullable=False),
    Column("parameter_sha256", CHAR(64), nullable=False),
    Column("execution_model", JSONB, nullable=False),
    Column("transaction_cost_model", JSONB, nullable=False),
    Column("engine_version", Text, nullable=False),
    Column("random_seed", BigInteger, nullable=False),
    Column("status", VARCHAR(16), nullable=False),
    Column("created_at", _ts, nullable=False),
    Column("started_at", _ts),
    Column("finished_at", _ts),
    Column("error_summary", Text),
    Column("metadata", JSONB, nullable=False),
    schema="backtest",
)
run_instrument = Table(
    "run_instrument",
    backtest_metadata,
    Column("run_id", BigInteger, primary_key=True),
    Column("instrument_id", BigInteger, primary_key=True),
    Column("membership_valid_from", _ts),
    Column("membership_valid_to", _ts),
    Column("initial_weight", Float),
    schema="backtest",
)
run_market_series = Table(
    "run_market_series",
    backtest_metadata,
    Column("run_id", BigInteger, primary_key=True),
    Column("bar_series_id", BigInteger, primary_key=True),
    Column("series_role", VARCHAR(12), primary_key=True),
    Column("is_primary", Boolean, nullable=False),
    Column("execution_lag", Interval, nullable=False),
    Column("metadata", JSONB, nullable=False),
    schema="backtest",
)
decision_context = Table(
    "decision_context",
    backtest_metadata,
    Column("decision_context_id", BigInteger, primary_key=True),
    Column("run_id", BigInteger, nullable=False),
    Column("decision_seq", BigInteger, nullable=False),
    Column("decision_ts", _ts, nullable=False),
    Column("strategy_state_sha256", CHAR(64)),
    Column("input_manifest_uri", Text),
    Column("input_manifest_sha256", CHAR(64)),
    Column("metadata", JSONB, nullable=False),
    Column("created_at", _ts, nullable=False),
    schema="backtest",
)
decision_bar_input = Table(
    "decision_bar_input",
    backtest_metadata,
    Column("decision_context_id", BigInteger, primary_key=True),
    Column("input_no", Integer, primary_key=True),
    Column("input_role", VARCHAR(12), nullable=False),
    Column("bar_open_ts", _ts, nullable=False),
    Column("bar_series_id", BigInteger, nullable=False),
    Column("bar_revision_no", Integer, nullable=False),
    Column("bar_available_at", _ts, nullable=False),
    Column("effective_available_at", _ts, nullable=False),
    schema="backtest",
)
signal = Table(
    "signal",
    backtest_metadata,
    Column("signal_id", BigInteger, primary_key=True),
    Column("run_id", BigInteger, nullable=False),
    Column("instrument_id", BigInteger, nullable=False),
    Column("signal_ts", _ts, nullable=False),
    Column("signal_type", VARCHAR(16), nullable=False),
    Column("direction", VARCHAR(8), nullable=False),
    Column("target_quantity", _money),
    Column("intended_entry_price", _money),
    Column("stop_loss_price", _money),
    Column("take_profit_price", _money),
    Column("score", Float),
    Column("reason_code", Text),
    Column("payload", JSONB, nullable=False),
    Column("created_at", _ts, nullable=False),
    Column("decision_context_id", BigInteger),
    schema="backtest",
)
bt_order = Table(
    "bt_order",
    backtest_metadata,
    Column("order_id", BigInteger, primary_key=True),
    Column("run_id", BigInteger, nullable=False),
    Column("signal_id", BigInteger),
    Column("instrument_id", BigInteger, nullable=False),
    Column("client_order_key", Text, nullable=False),
    Column("submitted_at", _ts, nullable=False),
    Column("valid_until", _ts),
    Column("side", VARCHAR(4), nullable=False),
    Column("order_type", VARCHAR(16), nullable=False),
    Column("time_in_force", VARCHAR(8), nullable=False),
    Column("quantity", _money, nullable=False),
    Column("limit_price", _money),
    Column("stop_price", _money),
    Column("status", VARCHAR(16), nullable=False),
    Column("reject_reason", Text),
    Column("metadata", JSONB, nullable=False),
    schema="backtest",
)
fill = Table(
    "fill",
    backtest_metadata,
    Column("fill_id", BigInteger, primary_key=True),
    Column("run_id", BigInteger, nullable=False),
    Column("order_id", BigInteger, nullable=False),
    Column("instrument_id", BigInteger, nullable=False),
    Column("fill_ts", _ts, nullable=False),
    Column("price", _money, nullable=False),
    Column("quantity", _money, nullable=False),
    Column("commission_amount", _money, nullable=False),
    Column("slippage_amount", _money, nullable=False),
    Column("tax_amount", _money, nullable=False),
    Column("fee_currency_code", VARCHAR(12), nullable=False),
    Column("liquidity_flag", CHAR(1)),
    Column("execution_reference", JSONB, nullable=False),
    Column("created_at", _ts, nullable=False),
    Column("execution_key", Text),
    schema="backtest",
)
round_trip_trade = Table(
    "round_trip_trade",
    backtest_metadata,
    Column("trade_id", BigInteger, primary_key=True),
    Column("run_id", BigInteger, nullable=False),
    Column("instrument_id", BigInteger, nullable=False),
    Column("entry_signal_id", BigInteger),
    Column("exit_signal_id", BigInteger),
    Column("direction", VARCHAR(8), nullable=False),
    Column("entry_ts", _ts, nullable=False),
    Column("exit_ts", _ts),
    Column("quantity", _money, nullable=False),
    Column("average_entry_price", _money, nullable=False),
    Column("average_exit_price", _money),
    Column("gross_pnl", _money),
    Column("commission_amount", _money, nullable=False),
    Column("slippage_amount", _money, nullable=False),
    Column("tax_amount", _money, nullable=False),
    Column("other_cost_amount", _money, nullable=False),
    Column("net_pnl", _money),
    Column("return_fraction", Float),
    Column("maximum_favorable_excursion", Float),
    Column("maximum_adverse_excursion", Float),
    Column("status", VARCHAR(8), nullable=False),
    schema="backtest",
)
trade_fill_allocation = Table(
    "trade_fill_allocation",
    backtest_metadata,
    Column("trade_id", BigInteger, primary_key=True),
    Column("fill_id", BigInteger, primary_key=True),
    Column("leg_type", VARCHAR(8), primary_key=True),
    Column("allocated_quantity", _money, nullable=False),
    schema="backtest",
)
order_event = Table(
    "order_event",
    backtest_metadata,
    Column("order_event_id", BigInteger, primary_key=True),
    Column("run_id", BigInteger, nullable=False),
    Column("order_id", BigInteger, nullable=False),
    Column("instrument_id", BigInteger, nullable=False),
    Column("event_seq", Integer, nullable=False),
    Column("event_key", Text, nullable=False),
    Column("event_ts", _ts, nullable=False),
    Column("event_type", VARCHAR(20), nullable=False),
    Column("status_after", VARCHAR(16), nullable=False),
    Column("source_fill_id", BigInteger),
    Column("filled_quantity_delta", _money),
    Column("remaining_quantity", _money),
    Column("event_price", _money),
    Column("reason_code", Text),
    Column("payload", JSONB, nullable=False),
    Column("recorded_at", _ts, nullable=False),
    schema="backtest",
)
fill_market_reference = Table(
    "fill_market_reference",
    backtest_metadata,
    Column("fill_id", BigInteger, primary_key=True),
    Column("reference_no", SmallInteger, primary_key=True),
    Column("run_id", BigInteger, nullable=False),
    Column("instrument_id", BigInteger, nullable=False),
    Column("reference_role", VARCHAR(12), nullable=False),
    Column("reference_type", VARCHAR(8), nullable=False),
    Column("bar_open_ts", _ts),
    Column("bar_series_id", BigInteger),
    Column("bar_revision_no", Integer),
    Column("bar_available_at", _ts),
    Column("effective_available_at", _ts),
    Column("model_price", _money),
    Column("metadata", JSONB, nullable=False),
    schema="backtest",
)
cash_ledger = Table(
    "cash_ledger",
    backtest_metadata,
    Column("cash_entry_id", BigInteger, primary_key=True),
    Column("run_id", BigInteger, nullable=False),
    Column("entry_ts", _ts, nullable=False),
    Column("currency_code", VARCHAR(12), nullable=False),
    Column("entry_type", VARCHAR(24), nullable=False),
    Column("amount", _money, nullable=False),
    Column("fill_id", BigInteger),
    Column("trade_id", BigInteger),
    Column("corporate_action_id", BigInteger),
    Column("fx_rate_to_base", _money),
    Column("metadata", JSONB, nullable=False),
    Column("source_key", Text),
    schema="backtest",
)
position_ledger = Table(
    "position_ledger",
    backtest_metadata,
    Column("position_entry_id", BigInteger, primary_key=True),
    Column("run_id", BigInteger, nullable=False),
    Column("instrument_id", BigInteger, nullable=False),
    Column("event_ts", _ts, nullable=False),
    Column("entry_type", VARCHAR(20), nullable=False),
    Column("quantity_delta", _money, nullable=False),
    Column("unit_cost_base", _money),
    Column("fill_id", BigInteger),
    Column("corporate_action_id", BigInteger),
    Column("source_key", Text, nullable=False),
    Column("metadata", JSONB, nullable=False),
    Column("recorded_at", _ts, nullable=False),
    schema="backtest",
)
position_snapshot = Table(
    "position_snapshot",
    backtest_metadata,
    Column("run_id", BigInteger, primary_key=True),
    Column("instrument_id", BigInteger, primary_key=True),
    Column("snapshot_ts", _ts, primary_key=True),
    Column("quantity", _money, nullable=False),
    Column("average_cost", _money),
    Column("market_price", _money),
    Column("market_value_base", _money),
    Column("realized_pnl_base", _money, nullable=False),
    Column("unrealized_pnl_base", _money, nullable=False),
    Column("margin_used_base", _money, nullable=False),
    schema="backtest",
)
position_valuation_bar_reference = Table(
    "position_valuation_bar_reference",
    backtest_metadata,
    Column("run_id", BigInteger, primary_key=True),
    Column("instrument_id", BigInteger, primary_key=True),
    Column("snapshot_ts", _ts, primary_key=True),
    Column("bar_open_ts", _ts, nullable=False),
    Column("bar_series_id", BigInteger, nullable=False),
    Column("bar_revision_no", Integer, nullable=False),
    Column("bar_available_at", _ts, nullable=False),
    Column("effective_available_at", _ts, nullable=False),
    Column("price_field", VARCHAR(16), nullable=False),
    schema="backtest",
)
equity_point = Table(
    "equity_point",
    backtest_metadata,
    Column("run_id", BigInteger, primary_key=True),
    Column("event_ts", _ts, primary_key=True),
    Column("cash_base", _money, nullable=False),
    Column("equity_base", _money, nullable=False),
    Column("gross_exposure_base", _money, nullable=False),
    Column("net_exposure_base", _money, nullable=False),
    Column("drawdown_fraction", Float),
    schema="backtest",
)
run_summary = Table(
    "run_summary",
    backtest_metadata,
    Column("run_id", BigInteger, primary_key=True),
    Column("total_return", Float),
    Column("annualized_return", Float),
    Column("annualized_volatility", Float),
    Column("sharpe_ratio", Float),
    Column("sortino_ratio", Float),
    Column("max_drawdown", Float),
    Column("win_rate", Float),
    Column("profit_factor", Float),
    Column("exposure_fraction", Float),
    Column("turnover_fraction", Float),
    Column("trade_count", BigInteger, nullable=False),
    Column("winning_trade_count", BigInteger, nullable=False),
    Column("losing_trade_count", BigInteger, nullable=False),
    Column("gross_pnl_base", _money),
    Column("net_pnl_base", _money),
    Column("total_cost_base", _money),
    Column("calculation_version", Text, nullable=False),
    Column("annualization_basis", JSONB, nullable=False),
    Column("calculated_at", _ts, nullable=False),
    schema="backtest",
)

BACKTEST_MAPPED_TABLES = tuple(backtest_metadata.tables.values())

__all__ = ["BACKTEST_MAPPED_TABLES", "backtest_metadata"]
